### PR TITLE
Fix #JENKINS-30237

### PR DESCRIPTION
**Pull request by zowers**
works fine, please merge

### CODE REVIEW

**Comment by grossws** [comment]
This requires additional configuration in youtrack since `fixedinbuild` is not defined as alias by default.

**Comment by zowers** [comment]
hm, didn't know that
one more option - is to simply remove the "Fixed In Build " prefix, because build-id is itself a valid command

**Comment by erikzielke** [comment]
I believe the only solution is to make the command configurable, so that is what I have done, it is pushed to github, but not yet uploaded.
But thanks for the feedback and effort to create a pull request.

**Comment by zowers** [comment]
thank you!

**Comment by zowers** [comment]
```
<buildUpdateCommand>${YOUTRACK_BUILD_NAME}</buildUpdateCommand>
```
works perfectly fine

**Comment by erikzielke** [comment]
yes, at least as long as there is no other bundles with the same name as the build. And for the few different setups I tried it picked Fixed in build even if there was multiple bundle values with the same name, but I am not sure how the field to use is selected.
Thanks for the feedback.

**Pull request closed without merging**
